[proforma]
positive = [
    "AA",
    "A[+1]",
    "AA[+1]",
]
negative = [
    "A[UNIMODIFY:+2]",
    "A[+1]-",
]

[INT]
positive = [
    "0",
    "1",
    "12347163101713764196123",
    "00000000000",
]
negative = [
    "",
    "i",
    "+1",
    "000o00",
]

[aa]
positive = [
    "A",
    "U",
    "X",
    "a",
    "A[#g1]",
]
negative = [
    "aa",
    "Asn",
    "A[#g1",
    "A(A)",
]

[mod]
positive = [
    "[+1]",
    "[U:+1]",
    "[+23.092]",
    "[-23.092]",
    "[14|Obs:+14|UNIMOD:0034|U:methyl]",
]

[modMass] 
positive = [
    "23",
    "+23",
    "23.0",
    "+23.0",
    "U:23",
    "Obs:23",
]

[formula]
positive = [
    "N1H3",
    "NH3",
    "H1H1H1N1",
    "[15N]H3",
    "[15N1]H3",
    "UTeHe",
    "[ 15 N     1 ] H 1",
]
negative = [
    "Ht1",
    "15N1",
    "15 N 1 H 1",
    "[15NH3",
]

[adductIon]
positive = [
    "+H+",
    "1H1+1",
    "+1[1H1]+",
]
negative = [
    "1 1H1 1",
    "1H1"
]

[charge]
positive = [
    "/1",
    "/+1",
    "/1[+H+]",
    "/1[-e-]",
]