[proforma]
positive = [
    "AA",
    "A[+1]",
    "AA[+1]",
    "A(AAAA)[+1][+1]",
    "UWAKJDNLASNOIJPojkjjdakjn[U:Oxidation]",
    "[+1]-A[+1]-[+1]",
    "AA+AA",
    "EMK[XLMOD:02000#XL1]EVTKSE[XLMOD:02010#XL2]SK[#XL1]PEK[#XL2]AR",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[XLMOD:02001#XL1]SESPEK",
    "EM[Oxidation]EVEES[Phospho]PEK",
    "EM[R: Methionine sulfone]EVEES[O-phospho-L-serine]PEK",
    "EMEVTK[X:DSS#XL1]SESPEK",
    "EM[U:Oxidation]EVEES[U:Phospho]PEK",
    "EM[+15.9949]EVEES[+79.9663]PEK",
    "EM[U:+15.995]EVEES[U:+79.966]PEK",
    "EM[U:+15.995]EVEES[Obs:+79.978]PEK",
    "RTAAX[+367.0537]WT",
    "{Glycan:Hex}EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]",
    "[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK",
    "[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methyl]",
    "<[S-carboxamidomethyl-L-cysteine]@C>ATPEILTCNSIGCLK",
    "<[MOD:01090]@C>ATPEILTCNSIGCLK",
    "[Phospho]?EM[Oxidation]EVTSESPEK",
    "[Phospho][Phospho]?[Acetyl]-EM[Oxidation]EVTSESPEK",
    "EM[Oxidation]EVT[#g1]S[#g1]ES[Phospho#g1]PEK",
    "EM[Oxidation]EVT[#g1(0.01)]S[#g1(0.09)]ES[Phospho#g1(0.90)]PEK",
    "[Phospho#s1]?EM[Oxidation]EVT[#s1(0.01)]S[#s1(0.90)]ES[#s1(0.90)]PEK",
    "PROT(EOSFORMS)[+19.0523]ISK",
    "PROT(EOC[Carbamidomethyl]FORMS)[+19.0523]ISK",
    "SEQUEN[Formula:C12H20O2]CE",
    "SEQUEN[Formula:HN-1O2]CE",
    "SEQUEN[Formula:[13C2][12C-2]H2N]CE",
    "SEQUEN[Glycan:HexNAc]CE",
    "EMEVTK[XLMOD:02001#XL1]SESPEK[#XL1]",
    "EMEVTK[XLMOD:02001#XL1]SESPEK",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[XLMOD:02001#XL1]SESPEK",
    "ETFGD[MOD:00093#BRANCH]//R[#BRANCH]ATER",
    "(?DQ)NGTWEM[Oxidation]ESNENFEGYM[Oxidation]K",
    "ELVIS[Phospho|+79.966331]K",
    "ELVIS[Phospho|Obs:+79.978]K",
    "ELV[INFO:xxxxx]IS",
    "ELVIS[Phospho|INFO:newly discovered|INFO:really awesome]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created on 2021-06]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created by software Tool1]K",
    "<13C>ATPEILTVNSIGQLK",
    "EMEVEESPEK/2",
    "EMEVEESPEK+ELVISLIVER",
    "EMEVEESPEK/2+ELVISLIVER/3",
    "A[#XL1]//B[#XL1]+C[#XL1]//D[#XL1]",
    "<[Carbamidomethyl]@C>ATPEILTCNSIGCLK",
    "<[Oxidation]@C,M>MTPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term>ATPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term:A>ATPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term:A,N-term:B>ATPEILTCNSIGCLK",
]
negative = ["<D>A[UNIMODIFY:+2]+<D>A", "A[+1]-"]

[modGlobal]
positive = [
    "<[TMT6plex]@K,N-term>",
    "<[TMT6plex]@K,N-term:A>",
    "<[TMT6plex]@K,N-term:A,N-term:B>",
]

[INT]
positive = ["0", "1", "12347163101713764196123", "00000000000"]
negative = ["", "i", "+1", "000o00"]

[aa]
positive = ["A", "U", "X", "a", "A[#g1]"]
negative = ["aa", "Asn", "A[#g1", "A(A)"]

[mod]
positive = [
    "[+1]",
    "[U:+1]",
    "[+23.092]",
    "[-23.092]",
    "[14|Obs:+14|UNIMOD:0034|U:methyl]",
    "[Formula:C-1O-1]",
    "[Glycan:Hex1HexNAc2]",
]

[modMass]
positive = ["23", "+23", "23.0", "+23.0", "U:23", "Obs:23"]

[formula]
positive = [
    "N1H3",
    "NH3",
    "C-1O-1",
    "H1H1H1N1",
    "[15N]H3",
    "[15N1]H3",
    "UTeHe",
    "[ 15 N     1 ] H 1",
]
negative = ["Ht1", "15N1", "15 N 1 H 1", "[15NH3"]

[adductIon]
positive = ["+H+", "1H1+1", "+1[1H1]+", "2Fe1+3"]
negative = ["1 1H1 1", "1H1"]

[charge]
positive = [
    "/1",
    "/+1",
    "/-1",
    "/1[+H+]",
    "/1[-e-]",
    "/7[2Fe1+3,+H+]",
    "/7[+2Fe1+3,1H1+1]",
    "/1[-OH-]",
    "/1[+N1H3+]",
    "/1[+[15N1]H3+]",
]
