[proforma]
positive = [
    "AA",
    "A[+1]",
    "AA[+1]",
]
negative = [
    "A[UNIMODIFY:+2]",
    "A[+1]-",
]

[INT]
positive = [
    "0",
    "1",
    "12347163101713764196123",
    "00000000000",
]
negative = [
    "",
    "i",
    "+1",
    "000o00",
]